# These are supported funding model platforms

github: Jack-Gledhill # Replace with up to 4 GitHub usernames that are enrolled in the Sponsorship programme
patreon: milabot
open_collective: # Replace with a single Open Collective username
ko_fi: milabot
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: https://paypal.me/robojack # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']