# ================
# General settings
# ================
server:
    host: "0.0.0.0"
    port: 5000

file_optimisation:
    compress: yes
    quality: 85

allowed_extensions:
    - png
    - jpg
    - gif

max_file_size: 
    megabytes: 2
    kilobytes: 0

logging:
    level: INFO

generator:
    filename: 8
    token: 56

figlet: 
    boot: MSGs Imago
    exit: Goodbye
    font: standard

version:
    major: 1
    minor: 1
    patch: 0
    release: stable

# ================
# Superuser config
# ================
superuser:
    username: superuser
    password: youshallnotpass

    display_name: Administrator
    api_token: Master youshallnotpass 

# =================
# External services
# =================
discord:
    enabled: true
    
    webhooks:
        - url: https://discordapp.com/api/webhooks/channel/token
          username: Imago Dashboard
          events:
            - IMAGE_DELETE # image deleted by its owner
            - IMAGE_UPLOAD # image uploaded
            - USER_EDIT # user has edited their account
            - USER_TOKEN_RESET # user has reset their token

        - url: https://discordapp.com/api/webhooks/channel/token
          username: Imago Admin Dashboard
          events:
            - FORCE_USER_CREATE # admin created a user
            - FORCE_USER_EDIT # admin edited a user by force
            - FORCE_USER_DELETE # admin deleted a user by force
            - FORCE_USER_TOKEN_RESET # admin reset a user's token by force
            - FORCE_IMAGE_DELETE # admin deleted an image by force
            - ADMIN_TOGGLE_ON # superuser made a user admin
            - ADMIN_TOGGLE_OFF # superuser removed admin from a user

postgres:
    user: user
    password: youshallnotpass

    port: 5432
    host: 127.0.0.1

    database: imago

honeybadger:
    enabled: true
    key: <key>