# ================
# General settings
# ================
default_locale: en-US # available locales are listed in /locales; Dutch locale is incomplete

server:
    host: "0.0.0.0"
    port: 5000

file_archive:
    enabled: true

file_optimisation:
    compress: yes
    quality: 85

    admin_bypass:
        can_bypass: yes
        by_default: no
        header: Compression-Bypass

url_shortening:
    custom_url:
        admin_only: yes
        header: URL-Name

allowed_extensions:
    png: image
    jpg: image
    ico: image

    mov: video
    mp4: video
    gif: gif

    wav: audio
    mp3: audio

    txt: other

max_file_size: 
    megabytes: 2
    kilobytes: 0

logging:
    level: INFO

generator:
    files: 8
    urls: 3
    token: 56

figlet: 
    boot: MSGs Imago
    exit: Goodbye
    font: standard

version:
    major: 3
    minor: 2
    patch: 1
    release: stable

# ================
# Superuser config
# ================
superuser:
    username: superuser
    password: youshallnotpass

    display_name: Administrator
    api_token: Master youshallnotpass 

# =================
# External services
# =================
discord:
    enabled: true
    
    webhooks:
        - url: https://discordapp.com/api/webhooks/channel/token
          username: Imago Dashboard
          events:
            - IMAGE_DELETE # image deleted by its owner
            - IMAGE_UPLOAD # image uploaded
            - URL_SHORTEN # url shortened
            - URL_DELETE # shortened url deleted
            - USER_EDIT # user has edited their account
            - USER_TOKEN_RESET # user has reset their token

        - url: https://discordapp.com/api/webhooks/channel/token
          username: Imago Admin Dashboard
          events:
            - FORCE_USER_CREATE # admin created a user
            - FORCE_USER_EDIT # admin edited a user by force
            - FORCE_USER_DELETE # admin deleted a user by force
            - FORCE_USER_TOKEN_RESET # admin reset a user's token by force
            - FORCE_IMAGE_DELETE # admin deleted an image by force
            - FORCE_URL_DELETE # admin deleted a shortened url
            - ADMIN_TOGGLE_ON # superuser made a user admin
            - ADMIN_TOGGLE_OFF # superuser removed admin from a user

postgres:
    user: user
    password: youshallnotpass

    port: 5432
    host: 127.0.0.1

    database: imago

honeybadger:
    enabled: true
    key: <key>